<?php
defined('ABSPATH') || exit;

/** Durable C3 report state; target lifecycle remains owned by the publisher. */
final class TNet_Community_Moderation_Repository {
    private array $tables;
    public function __construct() { $this->tables = TNet_Community_Schema::table_names(); }
    public function find(string $report_id): ?array { global $wpdb; return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->tables['reports']} WHERE report_id=%s LIMIT 1", $report_id), ARRAY_A) ?: null; }
    public function find_by_submission(string $reporter_id, string $key): ?array { global $wpdb; return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->tables['reports']} WHERE reporter_id=%s AND idempotency_key=%s LIMIT 1", $reporter_id, $key), ARRAY_A) ?: null; }
    public function queue(): array { global $wpdb; return $wpdb->get_results("SELECT report_id,target_post_id,target_type,community_id,reason_code,note,state,created_at,updated_at,resolved_at,resolved_by,resolution_code FROM {$this->tables['reports']} WHERE state IN ('open','under_review') ORDER BY created_at ASC, id ASC", ARRAY_A) ?: []; }
    public function audit(string $report_id): array { global $wpdb; return $wpdb->get_results($wpdb->prepare("SELECT * FROM {$this->tables['report_audit']} WHERE report_id=%s ORDER BY audit_id ASC", $report_id), ARRAY_A) ?: []; }
    public function create_in_transaction(array $row): array { global $wpdb; if (false === $wpdb->insert($this->tables['reports'], $row, array_fill(0, count($row), '%s'))) throw new RuntimeException('REPORT_WRITE_FAILED'); $audit=['report_id'=>$row['report_id'],'action'=>'reported','actor_id'=>$row['reporter_id'],'previous_state'=>null,'new_state'=>'open','reason'=>'user report submitted','evidence_json'=>wp_json_encode(['reporter_private'=>true]),'created_at'=>$row['created_at']]; if (false === $wpdb->insert($this->tables['report_audit'], $audit, array_fill(0, count($audit), '%s'))) throw new RuntimeException('REPORT_AUDIT_WRITE_FAILED'); return $this->find($row['report_id']) ?: throw new RuntimeException('REPORT_READ_FAILED'); }
    public function resolve_in_transaction(string $report_id, string $actor_id, string $state, string $resolution, ?string $target_action = null, ?array $transition = null): array { global $wpdb; $report=$this->find($report_id); if (!$report) throw new RuntimeException('REPORT_NOT_FOUND'); if (!in_array($report['state'], ['open','under_review'], true)) throw new RuntimeException('REPORT_ALREADY_RESOLVED'); $now=current_time('mysql',true); $ok=$wpdb->update($this->tables['reports'],['state'=>$state,'updated_at'=>$now,'resolved_at'=>$now,'resolved_by'=>$actor_id,'resolution_code'=>$resolution],['report_id'=>$report_id],['%s','%s','%s','%s','%s'],['%s']); if (false === $ok) throw new RuntimeException('REPORT_RESOLVE_WRITE_FAILED'); $audit=['report_id'=>$report_id,'action'=>$resolution,'actor_id'=>$actor_id,'previous_state'=>$report['state'],'new_state'=>$state,'reason'=>$resolution,'evidence_json'=>wp_json_encode(['target_action'=>$target_action,'transition'=>$transition]),'created_at'=>$now]; if (false === $wpdb->insert($this->tables['report_audit'], $audit, array_fill(0, count($audit), '%s'))) throw new RuntimeException('REPORT_AUDIT_WRITE_FAILED'); return $this->find($report_id) ?: throw new RuntimeException('REPORT_READ_FAILED'); }
}
