<?php
defined('ABSPATH') || exit;
final class TNet_Community_Landing_Controller {
    public static function register(): void { if(!self::local())return; add_rewrite_rule('^community/?$','index.php?tnet_community_landing=1','top'); add_filter('query_vars',static function(array $vars):array{$vars[]='tnet_community_landing';return $vars;}); add_action('template_redirect',[self::class,'render']); }
    private static function local(): bool { return defined('DDEV_PROJECT')||(bool)getenv('DDEV_PROJECT'); }
    public static function render(): void { if(!get_query_var('tnet_community_landing'))return; $rows=(new TNet_Community_Landing_View())->latest(); status_header(200);nocache_headers();header('X-Robots-Tag: noindex, nofollow');$base=home_url('/community/thread/'); echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Community Activity | Teachers.Net</title><style>body{font-family:system-ui,sans-serif;max-width:860px;margin:2rem auto;padding:0 1rem;line-height:1.5;color:#1d2327}.community-header{border-bottom:1px solid #ccd0d4;margin-bottom:1.5rem;padding-bottom:1rem}.community-header h1{margin:0 0 .25rem}.community-header p,.feed-meta,.empty-state,.feed-excerpt{color:#646970}.feed{display:grid;gap:1rem}.feed-card{border:1px solid #ccd0d4;border-radius:8px;padding:1rem;background:#fff}.feed-card h2{font-size:1.2rem;margin:.2rem 0 .4rem}.feed-card h2 a{color:#135e96}.feed-meta{font-size:.9rem;margin:0}.feed-excerpt{margin:.5rem 0}.card-media,.card-preview{border:1px solid #dcdcde;border-radius:6px;background:#f6f7f7;padding:1rem;margin:.8rem 0}.card-media.image{min-height:6rem;display:grid;place-items:center}.card-media p,.card-preview p{margin:.25rem 0}.start-discussion{background:#135e96;color:#fff;border:0;border-radius:4px;padding:.65rem 1rem;font:inherit;font-weight:600;text-decoration:none;display:inline-block}.feed-card:focus-within{outline:3px solid #b8d4ee;outline-offset:2px}@media(max-width:520px){body{margin:1rem auto}.feed-card{padding:.85rem}}</style></head><body><main><header class="community-header"><p>Teachers.Net Community</p><h1>Activity</h1><p>Recent conversations from teachers and education professionals.</p><a class="start-discussion" href="'.esc_url(home_url('/community/new/')).'">Start a Discussion</a></header><section aria-labelledby="activity-heading"><h2 id="activity-heading">Latest Activity</h2>';
        if(!$rows)echo '<p class="empty-state">There is no activity to show yet. Check back soon.</p>'; else {echo '<div class="feed">';foreach($rows as $row){$url=trailingslashit($base.$row['post_id']);$body=(string)($row['body']??'');$excerpt=wp_trim_words(wp_strip_all_tags($body),32);$truncated=$excerpt!==wp_trim_words(wp_strip_all_tags($body),9999);$text=$truncated?wp_trim_words(wp_strip_all_tags($body),32):$body;echo '<article class="feed-card"><p class="feed-meta">'.esc_html($row['author_display']).' · '.esc_html($row['last_activity']).'</p><h2><a href="'.esc_url($url).'">'.esc_html($row['title']).'</a></h2><div class="feed-excerpt"'.($truncated?' data-expandable="true" tabindex="0" role="button" aria-expanded="false" aria-label="Read full post"':'').'><span class="feed-excerpt-collapsed">'.TNet_Community_Authoring::markdown($text).'</span>'.($truncated?'<span class="feed-excerpt-expanded" hidden>'.TNet_Community_Authoring::markdown($body).'</span>':'').'</div>'.self::media($row).'<p class="feed-meta">'.esc_html(number_format_i18n($row['reply_count'])).' '.esc_html(_n('reply','replies',$row['reply_count'],'tnet-community')).' · <a href="'.esc_url($url).'">Open conversation</a></p></article>';}echo '</div><script>(function(){document.querySelectorAll("[data-expandable]").forEach(function(el){function expand(e){if(e&&e.target.closest("a,button,img,.card-preview,.story-image,video,audio"))return;if(el.getAttribute("aria-expanded")==="true")return;el.setAttribute("aria-expanded","true");el.setAttribute("aria-label","Full post");el.querySelector(".feed-excerpt-collapsed").hidden=true;el.querySelector(".feed-excerpt-expanded").hidden=false}el.addEventListener("click",expand);el.addEventListener("keydown",function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();expand(e)}})} })();</script>';}
        echo '</section></main></body></html>';exit; }
    private static function media(array $row): string { $html='';foreach($row['attachments'] as $a){if(($a['moderation_state']??'clear')!=='clear')continue;$html.=TNet_Community_Attachment::render($a);} return $html.TNet_Community_Link_Preview::render($row['preview']??[]); }
}
